### ISSUE TITLE
VLI image contains grub2 for aarch64

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/keg-recipes#104]
The VLI image should not contain the grub2-arm64-efi package. VLI images are for x86-64 only and based on the SLE For SAP product which is not available for aarch64

**Comment by jgleissner** [comment]
Well, it's not actually in the images, but it is in the image descriptions. It gets included from `data/csp/sle15/profile_defaults.yaml`. It includes this in basically everything, and ends up as a kind of a no-op in x86_64 only builds.

Excluding this from all SAP and SUMa builds is actually more fiddly than one might think. The grub package is included in the CSP specific profiles, and the product modules is in common profile, so the product module can't overwrite it. It could be easily removed from Azure LI/VLI though.

**Comment by rjschwei** [comment]
Yes, it's not in the image, that is correct. Lets' start with removing it from the LI/VLI images and try and figure a more elegant way to handle architecture. Maybe the arch needs to bubble up to the command line rather than being implicit to the image build.

**Comment by jgleissner** [comment]
This is handled via the architecture parameter for keg, which filters out packages for architectures that are not enabled.
