### ISSUE TITLE
Overlay tree is not correct for GCE HPC PAYG image

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/keg-recipes#106]
Should be the same as for the BYOS image. The BYOS image is correct. In the PAYG version limits.d settings are missing for example.

**Comment by rjschwei** [comment]
That said in the BYOS image it looks like `etc/motd.d/30-mgmt` appears to be missing

**Comment by jgleissner** [comment]
`/etc/motd.d/30-mgmt` is only in on-demand images. I think I initially only added SLE-HPC BYOS for GCE as we didn't have an on-demand GCE build in the SUSE namespace and never added the appropriate overlay config for on-demand. I'll fix it.

**Comment by jgleissner** [comment]
Fix was merged.
