### ISSUE TITLE
Add recipes for SAPCAL images

### ISSUE THREAD

**Issue by aosthof** [SUSE-Enceladus/keg-recipes#112]
So far there's only the SLES 15 SP1 SAPCAL image available in keg-recipes. Each of the following versions need to be added for AWS, Azure and GCE, on-demand only:

- SLES 15 SP4 SAPCAL
- SLES 15 SP3 SAPCAL
- SLES 12 SP3 SAPCAL

**Comment by jgleissner** [comment]
We're not handling SLES 12 SP3 in keg-recipes. I'll add the other ones.

**Comment by jgleissner** [comment]
Related PRs: https://github.com/SUSE-Enceladus/keg-recipes/pull/113 https://github.com/SUSE-Enceladus/keg-recipes/pull/114

**Comment by jgleissner** [comment]
Added a while ago.
