### ISSUE TITLE
Feature: Add ConvergeCloud as Provider

### ISSUE THREAD

**Issue by killermoehre** [SUSE-Enceladus/keg-recipes#185]
It was decided that SUSE will build a CHost image consumable by SAP ConvergedCloud.

This image should mirror the OpenStack one with added package `open-vm-tools`.

**Comment by sandzwerg** [comment]
Image format should be streamoptimized vmdk. Which we till now build with

```
<type image="oem" filesystem="xfs" format="vmdk" firmware="uefi" kernelcmdline="plymouth.enable=0 net.ifnames=1 earlyprintk=efi,keep product_name='OpenStack Nova' consoleblank=0" bootpartition="false">
      <machine arch="x86_64" ovftype="vmware" memory="1024" HWversion="10" guestOS="sles12_64Guest"> 
<vmdisk diskmode="streamOptimized"/>
```

Probably only the `format="vmdk"`, `ovftype="vmware"` `HWversion="10"` and `<vmdisk diskmode="streamOptimized"/>` is needed
