### ISSUE TITLE
empty lines after template render

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/keg-recipes#9]
These jinja templates renders empty lines at several places. There is an opportunity to influence this by the ```{%-``` (+/-) notation but after hours of playing with this I still failed to let it work the way I wanted.

@jgleissner if you could have a look at this it would be very much appreciated. Only the config.sh and images.sh templates are affected by this issue

Thanks

**Comment by jgleissner** [comment]
Whitespace handling in jinja2 is a huge pain in the butt. I take a look when I have a chance.

**Comment by jgleissner** [comment]
With https://github.com/SUSE-Enceladus/keg-recipes/pull/17 this should be solved.
